# LASER
LASER_X: -0.17
LASER_Y: 0.0
LASER_Z: 0.845
LASER_ROLL: 0.0
LASER_PITCH: 0.0
LASER_YAW: 0.0

# CAMERA
CAMERA_X: -0.22
CAMERA_Y: 0.0
CAMERA_Z: 0.72
CAMERA_ROLL: 0.0
CAMERA_PITCH: 0.0
CAMERA_YAW: 0.0